export enum FilterType {
  CITY,
  GENDER_TYPE,
  APARTMENT_CONDITIONS,
  APARTMENT_FURNITURE,
  APARTMENT_FACILITIES,
  APARTMENT_BATHROOM_TYPES,
  APARTMENT_FURNITURE_STATUSES,
  APARTMENT_BATHROOMS,
  APARTMENT_SECURITIES,
  WINDOW_DIRECTIONS,
  APARTMENT_FOR,
}
